Pull Request - nav_branch
tawakuliKH/portofolio pull request #1
Opened 2023-01-19 21:16 UTC by tawakuliKH

Added html and css files.

2023-01-19 23:19 UTC, Kossi-stack requested changes
## Hi @tawakuliKH,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly edit the PR's title to something more descriptive. it can be "Portfolio: setup PR"

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-19 23:19 UTC, Kossi-stack commented on index.html
> +            <div class="vector"><img src="assets/vector.svg" alt="vector"></div>
- [x] Kindly use a nav tag for hamburger
The nav tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-01-19 23:19 UTC, Kossi-stack commented on index.html
> +        <div class="social">
- [ ] Kindly put The list of icons in a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag)
the `a` tag will let you connect your social networks with the icons, using href.

2023-01-19 23:19 UTC, Kossi-stack commented on index.html
> +            <div class="mylogo"><a class="logo">My Logo</a></div>
- [ ] Kindly remove the div and leave it in a tag
because of convention, semantics, and user experience(UX).

2023-01-20 08:24 UTC, Ibizugbe approved these changes
Hi @tawakuliKH 👋, 

![BigTvGIF (2)](https://user-images.githubusercontent.com/64643995/213649517-4831d6a0-ff65-456b-8e5b-5114f410377a.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅
- linters are passing👍
- commit messages are meaningful👍
- github flow has been used👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 08:25 UTC, merged